import React,{useState,useEffect,useRef,Suspense,lazy} from 'react';
import {createRoot} from 'react-dom/client';
import {MapPin,Heart,Ticket,UtensilsCrossed,Store,Check,Plus,Minus,Menu,X,SlidersHorizontal,ScanLine,Users,MousePointer2,ExternalLink,ArrowUpRight,ArrowRight} from 'lucide-react';
import './style.css';
import Universe,{StoryJourney} from './Universe';
import './world.css';
import './refinement.css';
import './cinema.css';
const CouponScene=lazy(()=>import('./CouponScene'));

type Role='consumer'|'merchant';

function App(){
 const [role,setRole]=useState<Role>(new URLSearchParams(location.search).get('view')==='merchants'?'merchant':'consumer');const merchant=role==='merchant';const [menu,setMenu]=useState(false);const [faq,setFaq]=useState<number|null>(0);const [modal,setModal]=useState<'explore'|'contact'|null>(null);const menuDialog=useRef<HTMLDialogElement>(null);const dialog=useRef<HTMLDialogElement>(null);
 function switchRole(r:Role){setRole(r);setFaq(0);setMenu(false);const u=new URL(location.href);u.searchParams.set('view',r==='merchant'?'merchants':'consumers');history.replaceState({},'',u);}
 useEffect(()=>{if(menu){menuDialog.current?.showModal();document.body.style.overflow='hidden';}else{menuDialog.current?.close();document.body.style.overflow='';}return()=>{document.body.style.overflow='';};},[menu]);
 useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close();},[modal]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');observer.unobserve(e.target);}});},{threshold:.12});document.querySelectorAll('.section-heading,.food-card,.merchant-card,.experience-copy,.story-copy,.faq').forEach(el=>{el.classList.add('reveal');observer.observe(el);});return()=>observer.disconnect();},[role]);
 const questions=merchant?[['How do I get started?','Tell us about your restaurant and location. Our team can walk you through the available programs, offer setup, and next steps.'],['Can I choose when an offer is available?','Offer planning can include eligible times, quantities, and redemption conditions. Your final campaign details are agreed with the CrazyBee team.'],['Do I need to change my POS?','For the dine-in deal program described in our merchant materials, you keep your existing POS workflow. Guests redeem their deal and pay in-store according to the offer terms.']]:[['How do CrazyBee deals work?','Discover an offer, read its terms, and follow the purchase or claim instructions. For dine-in offers, show your redemption code at the restaurant. Payment and redemption rules vary by offer.'],['Are all offers available everywhere?','Availability depends on the restaurant, location, and program. Always check the location, valid times, and offer conditions before purchasing.'],['Where can I find group delivery?','Group delivery has its own ordering experience. Open Explore CrazyBee and choose Group delivery to see currently available menus, pickup locations, and sessions.']];
 return <><header className="header"><a className="wordmark" href="#world" aria-label="CrazyBee home"><img src="/assets/brand-logo.svg" alt="CrazyBee"/></a><a className="header-discover" href="#discover">Find your place <ArrowUpRight size={14}/></a><button className="menu-trigger" aria-label="Open menu" aria-haspopup="dialog" aria-expanded={menu} onClick={()=>setMenu(true)}><span>Menu</span><span className="menu-lines"><i/><i/></span></button></header>
 <dialog className="site-menu" ref={menuDialog} aria-label="Site navigation" onCancel={()=>setMenu(false)}><div className="menu-top"><img src="/assets/brand-logo.svg" alt="CrazyBee"/><button aria-label="Close menu" onClick={()=>setMenu(false)}>Close <X size={19}/></button></div><div className="menu-body"><div className="menu-caption"><span>GOOD FOOD.<br/>REAL CONNECTIONS.</span><p>A little closer to<br/>your next favorite.</p></div><nav aria-label="Main navigation">{[['01','Explore the world','world'],['02','The simple idea','the-idea'],['03','For you & your business','discover'],['04','How it works','how'],['05','Our story','story']].map(([n,label,id],i)=><a style={{'--delay':`${i*65}ms`} as React.CSSProperties} key={id} href={'#'+id} onClick={()=>setMenu(false)}><small>{n}</small><span>{label}</span><ArrowUpRight/></a>)}</nav></div><div className="menu-footer"><a href="mailto:business@crazybee.life">business@crazybee.life <ArrowUpRight size={14}/></a><span>Discover local. Feel connected.</span></div></dialog>
 <main><Universe merchant={merchant} onAction={()=>setModal(merchant?'contact':'explore')} onStory={()=>document.getElementById('story')?.scrollIntoView({behavior:'smooth'})}/><StoryJourney merchant={merchant}/>
 <section className="section discover" id="discover"><div className="section-heading"><div><span className="eyebrow">03 — A PLACE FOR YOU</span><h2>Good for your day.<br/><span>Good for your neighborhood.</span></h2></div><p>CrazyBee connects people with local restaurants through dine-in deals and shared food experiences.</p></div>
 <div className="audience-tabs" role="tablist" aria-label="Choose your experience" onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'consumer':e.key==='End'?'merchant':merchant?'consumer':'merchant';switchRole(next);requestAnimationFrame(()=>document.getElementById(next+'-tab')?.focus());}}}><button id="consumer-tab" role="tab" tabIndex={merchant?-1:0} aria-selected={!merchant} aria-controls="audience-content" onClick={()=>switchRole('consumer')}>For you <span>01</span></button><button id="merchant-tab" role="tab" tabIndex={merchant?0:-1} aria-selected={merchant} aria-controls="audience-content" onClick={()=>switchRole('merchant')}>For merchants <span>02</span></button></div>
 <div className="service-layout" id="audience-content" role="tabpanel" aria-labelledby={merchant?'merchant-tab':'consumer-tab'} key={role}><div className="service-intro"><span className="eyebrow">{merchant?'YOUR RESTAURANT, CONNECTED':'LOCAL FOOD, MORE POSSIBILITIES'}</span><h3>{merchant?<>Meet your next<br/>regular.</>:<>Your next good<br/>food moment.</>}</h3><p>{merchant?'Introduce your restaurant, shape your offers, and welcome more of your neighborhood.':'Find a place to eat, understand the offer, and make a little time for something good.'}</p><button className="editorial-link" onClick={()=>setModal(merchant?'contact':'explore')}>{merchant?'Explore a partnership':'Explore CrazyBee'} <ArrowUpRight size={18}/></button></div><div className="service-list">{(merchant?[{icon:Users,title:'Reach local diners',text:'Give nearby guests a reason to discover your restaurant with a thoughtful dine-in offer.',label:'DISCOVERY'},{icon:SlidersHorizontal,title:'Keep offers on your terms',text:'Plan valid times, quantities, and redemption conditions around your restaurant.',label:'CONTROL'},{icon:ScanLine,title:'Understand every redemption',text:'Use available redemption information to see which offers bring people through your door.',label:'INSIGHT'}]:[{icon:UtensilsCrossed,title:'Dine-in deals',text:'Discover restaurant offers. Check the location, valid times, and redemption details before you go.',label:'AT YOUR TABLE'},{icon:Users,title:'Group delivery',text:'Browse the existing ordering experience for available menus, pickup locations, and delivery sessions.',label:'BETTER TOGETHER'},{icon:Heart,title:'Local discoveries',text:'Get to know the restaurants around you — and find a new favorite worth coming back to.',label:'AROUND THE CORNER'}]).map((item,i)=><article className="service-row" key={item.title}><div className={'service-symbol symbol-'+i}><item.icon strokeWidth={1.2} size={27}/></div><div><span>{item.label}</span><h4>{item.title}</h4><p>{item.text}</p></div><small>0{i+1}</small></article>)}</div></div></section>
 <section className="experience" id="how"><div className="experience-copy"><span className="eyebrow">{merchant?'04 — HOW IT WORKS':'04 — HOW IT WORKS'}</span><h2>{merchant?<>Your offer.<br/>Your way.</>:<>A little deal.<br/>A lovely time.</>}</h2><p>{merchant?'From your first offer to your next regular, keep the experience simple.':'Good moments shouldn’t be complicated. Here’s how your next one begins.'}</p><ol className="steps">{(merchant?[['Tell us about your place','Connect with our team to find the right program.'],['Make an offer your own','Choose the details and conditions that fit your business.'],['Welcome your neighborhood','Redeem offers and keep doing what you do best.']]:[['Find your kind of place','Explore local restaurants and their available offers.'],['Get the details, get the deal','Check the offer’s times, terms, and payment details.'],['Show up. Settle in. Enjoy.','Redeem at the restaurant and make yourself at home.']]).map(([title,desc],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{desc}</p></div></li>)}</ol></div><div className="experience-art"><span className="demo-label">TWO SIDES. ONE GOOD CONNECTION.</span><Suspense fallback={<div className="scene-loading">A little good is on its way…</div>}><CouponScene merchant={merchant}/></Suspense><p className="scene-caption">A deal for you. A new connection for a local business.</p></div></section>
 <section className="story section" id="story"><div className="story-image"><img src="/assets/crazybee-cutout.png" alt="Our friendly CrazyBee mascot" loading="lazy"/><span className="handwritten">A little bee.<br/>A big love for local.</span></div><div className="story-copy"><span className="eyebrow">05 — WHY WE’RE HERE</span><h2>Good food brings<br/>us closer.</h2><p>There’s something special about finding a place you love. The people behind the counter. Your usual order. The friend you always bring along.</p><p>CrazyBee connects local restaurants with the people around them — through thoughtful offers, shared experiences, and more reasons to come back.</p><span className="story-signature">More than a deal. A little belonging. <Heart size={17}/></span></div></section>
 <section className="faq section"><div><span className="eyebrow">06 — THE DETAILS</span><h2>Glad you asked.</h2><p>A little clarity before you get started.</p></div><div className="faq-list">{questions.map(([q,a],i)=><div className="faq-item" key={q}><h3><button onClick={()=>setFaq(faq===i?null:i)} aria-expanded={faq===i} aria-controls={'answer-'+i}>{q}{faq===i?<Minus size={19}/>:<Plus size={19}/>}</button></h3><div id={'answer-'+i} hidden={faq!==i}><p>{a}</p></div></div>)}</div></section>
 <section className="closing"><span className="eyebrow">{merchant?'LET’S MAKE GOOD THINGS HAPPEN':'YOUR NEXT GOOD THING IS LOCAL'}</span><h2>{merchant?'Make room for new regulars.':'Go out. Eat well. Feel good.'}</h2><p>{merchant?'Let’s introduce your restaurant to the neighborhood.':'A new favorite is waiting to be found.'}</p><button className="primary light" onClick={()=>setModal(merchant?'contact':'explore')}>{merchant?'Let’s talk':'Explore CrazyBee'}</button><div className="closing-orbit" aria-hidden="true"/><span className="closing-note">A little discovery goes a long way.</span></section>
 </main><nav className="chapter-nav" aria-label="Jump to a chapter"><a href="#world">Explore</a><a href="#the-idea">The idea</a><a href="#discover">For you & business</a><a href="#how">How it works</a></nav><footer><a className="wordmark" href="#"><img src="/assets/brand-logo.svg" alt="CrazyBee"/></a><span>Good food. Real connections.</span><a href="mailto:business@crazybee.life">Get in touch</a><small>© {new Date().getFullYear()} CrazyBee</small></footer>
 <dialog aria-label={modal==='contact'?'Partner with CrazyBee':'Explore CrazyBee'} ref={dialog} onCancel={()=>setModal(null)} onClick={e=>{if(e.target===dialog.current)setModal(null)}}><button className="dialog-close" aria-label="Close dialog" onClick={()=>setModal(null)}><X/></button>{modal==='contact'?<><span className="eyebrow">HELLO, NEIGHBOR</span><h2>Let’s grow<br/>something good.</h2><p>Tell us your restaurant’s name, location, and the best way to reach you. Our team will help you explore the right program.</p><a className="primary" href="mailto:business@crazybee.life?subject=Partner%20with%20CrazyBee">Email our team <ExternalLink size={16}/></a><span className="dialog-small">business@crazybee.life</span></>:<><span className="eyebrow">YOUR NEXT LOCAL DISCOVERY</span><h2>A little something<br/>to look forward to.</h2><p>This is a preview of our new brand website. Browse the existing ordering experience for current group delivery availability.</p><a className="explore-option" href="https://order.crazybee.life/delivery" target="_blank" rel="noreferrer"><span className="note-icon"><UtensilsCrossed size={22}/></span><div><strong>Group delivery</strong><span>Check current menus and pickup sessions</span></div><ExternalLink size={18}/></a><div className="explore-option disabled"><span className="note-icon"><Store size={22}/></span><div><strong>Local dine-in deals</strong><span>Discovery experience shown in this preview</span></div><span className="preview-tag">Preview</span></div></>}</dialog>
 </>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
