import {lazy,Suspense,useRef,useState,useEffect} from 'react';
import {ArrowUpRight,ChevronLeft,ChevronRight,Pause,Play,RotateCcw,X,Plus,Check,MoveHorizontal} from 'lucide-react';
import ParticleMotif from './ParticleMotif';
import type {WorldHandle} from './WorldScene';
const Scene=lazy(()=>import('./WorldScene'));
const consumer=[{label:'Discover a little delicious',short:'Discover',title:'Follow your appetite.',text:'Comfort food or a new favorite? Pick a craving and give your next outing a little direction.',options:['Comfort classics','Something new','Made to share'],detail:['A familiar flavor. A favorite seat. Start with the local places that make you feel at home.','Make room for a different dish, a new corner, and a story you haven’t tasted yet.','Good food gets even better when there’s someone across the table.'],cta:'Explore CrazyBee'},{label:'Make room for together',short:'Connect',title:'Who’s at your table?',text:'A quick lunch, a long catch-up, or a little time for yourself. There’s a good moment for every table.',options:['Just me','A friend & me','The whole table'],detail:['A small pause in a busy day. Find something that makes your lunch hour yours.','One good meal. Two stories to catch up on. Make your next get-together local.','Pass a plate. Make a memory. Discover a new place together.'],cta:'Find your next favorite'},{label:'Meet your neighborhood',short:'Belong',title:'A favorite is a feeling.',text:'The restaurant you remember. The people you come back for. Explore what makes local matter.',options:['The food','The people','The little rituals'],detail:['Every neighborhood has a signature flavor. Discover the kitchens behind it.','The people behind the counter are part of what makes a meal special.','Your usual order. Your favorite corner. Small moments become a sense of belonging.'],cta:'Meet CrazyBee'}];
const merchants=[{label:'Welcome new faces',short:'Discover',title:'A first visit starts here.',text:'Introduce your restaurant through an offer that gives nearby diners a reason to walk in.',options:['A signature dish','A new menu item','An off-peak offer'],detail:['Put the dish you’re known for at the heart of your introduction.','Give curious diners a reason to try something new from your kitchen.','Build an offer around the times that work for your restaurant.'],cta:'Talk about your restaurant'},{label:'Shape your own offer',short:'Control',title:'Your restaurant. Your rules.',text:'Explore the building blocks of an offer. This is an interactive illustration, not a published campaign.',options:['Choose the time','Set the quantity','Pause when needed'],detail:['Decide when an offer is valid, and explain the available times clearly to guests.','Limit the offer to a quantity your team can comfortably serve.','Keep your offer aligned with your restaurant’s changing availability.'],cta:'Explore a partnership'},{label:'Give them a reason to return',short:'Return',title:'From a visit to a ritual.',text:'A thoughtful first experience opens the door to an ongoing neighborhood connection.',options:['A warm welcome','A reason to return','Learn what works'],detail:['A good deal brings curiosity. Your hospitality makes the lasting impression.','Keep your restaurant in mind with relevant offers and local stories.','Use available redemption information to understand which offers resonate.'],cta:'Grow with CrazyBee'}];
export default function Universe({merchant,onAction,onStory}:{merchant:boolean;onAction:()=>void;onStory:()=>void}){
 const [selected,setSelected]=useState<number|null>(null),[choice,setChoice]=useState(0),[paused,setPaused]=useState(false),[ready,setReady]=useState(false),[hello,setHello]=useState(false),[model,setModel]=useState(1);const panel=useRef<HTMLElement>(null);const api=useRef<WorldHandle|null>(null);const data=merchant?merchants:consumer;const item=selected===null?null:data[selected];
 useEffect(()=>{setSelected(null);setChoice(0);},[merchant]);useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setSelected(null);};addEventListener('keydown',close);return()=>removeEventListener('keydown',close);},[]);useEffect(()=>{if(!hello)return;const t=setTimeout(()=>setHello(false),2800);return()=>clearTimeout(t);},[hello]);
 useEffect(()=>{const card=panel.current;if(!card)return;const section=card.closest<HTMLElement>('.universe');const fit=()=>section?.style.setProperty('--panel-height',`${Math.ceil(card.getBoundingClientRect().height)+100}px`);const observer=new ResizeObserver(fit);observer.observe(card);fit();return()=>{observer.disconnect();section?.style.removeProperty('--panel-height');};},[selected]);
 useEffect(()=>{const change=(e:Event)=>setModel((e as CustomEvent<number>).detail);document.addEventListener('model-focus',change);return()=>document.removeEventListener('model-focus',change);},[]);
 useEffect(()=>{const hero=document.getElementById('world');if(!hero)return;const observer=new IntersectionObserver(([entry])=>document.documentElement.classList.toggle('hero-in-view',entry.isIntersecting),{rootMargin:'-85px 0px -65% 0px'});observer.observe(hero);return()=>{observer.disconnect();document.documentElement.classList.remove('hero-in-view');};},[]);
 const select=(i:number)=>{setSelected(i);setChoice(0);};
 return <section id="world" className={'universe '+(selected!==null?'destination-open':'')} aria-label="Explore the CrazyBee universe"><div className="world-wash"/><div className="cinema-glow" aria-hidden="true"/><div className="world-index"><span>CRAZYBEE — LOCAL FOOD, REAL CONNECTIONS</span><span>01 — EXPLORE YOUR WAY</span></div><div className="world-theme">A little world. A lot to discover.</div><div className="world-ghost" aria-hidden="true">a world of<br/><i>good food.</i></div><Suspense fallback={null}><Scene selected={selected} paused={paused} onChoose={select} onReady={()=>setReady(true)} api={api}/></Suspense>
 <div className="world-destinations" aria-label="Explore a destination">{data.map((d,i)=><button key={i} className={'destination destination-'+i+(selected===i?' selected':'')} aria-pressed={selected===i} onClick={()=>select(i)}><span className="destination-dot">{selected===i?<Check size={13}/>:<Plus size={13}/>}</span><span><small>0{i+1}</small>{d.label}</span></button>)}</div>
 <div className="world-bottom"><div className="world-intro" key={merchant?'merchant':'consumer'}><div className="world-kicker">{merchant?'FOR THE PLACES THAT BRING US TOGETHER':'GOOD FOOD IS ONLY THE BEGINNING'}</div><h1><span>{merchant?'More new faces.':'A world of flavor.'}</span><span>{merchant?'More familiar ones.':'Closer than you think.'}</span></h1><p>{merchant?'Connect your restaurant with the neighborhood.':'Local discoveries. Lovely little deals. Real connections.'}</p></div><div className="world-console"><p>A little discovery.<br/>A real local connection.</p><span className="ambient-hint">Move your cursor. Follow the glow.</span></div></div>
 <a href="#the-idea" className="world-scroll">Or, let us introduce ourselves <span>↓</span></a>
 {item&&<aside ref={panel} className="destination-panel" aria-label={item.title}><button className="panel-close" aria-label="Return to the world" onClick={()=>setSelected(null)}><X size={20}/></button><span className="panel-number">0{selected!+1} / {merchant?'FOR MERCHANTS':'FOR YOU'}</span><h2 key={item.title}>{item.title}</h2><p>{item.text}</p><div className="choice-tabs">{item.options.map((o,i)=><button key={o} onClick={()=>setChoice(i)} aria-pressed={choice===i}>{o}</button>)}</div><ParticleMotif choice={choice}/><p className="choice-description" key={item.title+choice} aria-live="polite">{item.detail[choice]}</p><button className="panel-action" onClick={()=>{if(selected===2&&!merchant){setSelected(null);onStory();}else onAction();}}>{item.cta}<ArrowUpRight size={18}/></button><div className="panel-next"><button onClick={()=>select((selected!+2)%3)}><ChevronLeft size={15}/>Previous</button><span>{selected!+1} / 3</span><button onClick={()=>select((selected!+1)%3)}>Next<ChevronRight size={15}/></button></div></aside>}
 </section>;
}
export function StoryJourney({merchant}:{merchant:boolean}){const ref=useRef<HTMLElement>(null);const [progress,setProgress]=useState(0);const [step,setStep]=useState(0);useEffect(()=>{const el=ref.current!;let frame=0;const tick=()=>{frame=0;const b=el.getBoundingClientRect();const p=Math.max(0,Math.min(1,-b.top/(el.offsetHeight-innerHeight)));setProgress(p);setStep(Math.min(2,Math.floor(p*3)));};const onScroll=()=>{if(!frame)frame=requestAnimationFrame(tick);};addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',onScroll);tick();return()=>{removeEventListener('scroll',onScroll);removeEventListener('resize',onScroll);cancelAnimationFrame(frame);};},[]);
 const content=merchant?[['A little discovery.','A new guest at your table.','Introduce your restaurant with a thoughtful local offer.'],['A little control.','An offer that fits your business.','Choose the timing, quantity, and conditions that work for you.'],['A little connection.','A reason to come back.','Turn a first impression into a place people remember.']]:[['A little discovery.','Your next favorite place.','Find local restaurants and explore their available offers.'],['A little clarity.','Know the deal before you go.','See where, when, and how an offer can be used.'],['A little connection.','More than a meal.','Show up, settle in, and make a little time for each other.']];
 return <section ref={ref} className="story-journey" id="the-idea"><div className="journey-sticky"><div className="journey-top"><span>02 — THE SIMPLE IDEA</span><span>GOOD THINGS, MADE SIMPLE.</span></div><div className="journey-title" key={step+(merchant?10:0)}><span>{content[step][0]}</span><h2>{content[step][1]}</h2><p>{content[step][2]}</p></div><div className={'journey-object journey-step-'+step}><div className="journey-ticket"><span>CRAZYBEE</span><strong>{['Discover.','Understand.','Enjoy.'][step]}</strong><small>LOCAL FOOD. REAL CONNECTIONS.</small></div><div className="journey-orbit"/><div className="journey-orbit second"/></div><div className="journey-bottom"><div className="journey-progress"><span style={{width:`${progress*100}%`}}/></div><div>{content.map((c,i)=><span key={c[0]} className={step===i?'active':''}>0{i+1} {['Discover','Understand','Connect'][i]}</span>)}</div></div></div></section>;
}
