import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowLeft,RotateCcw,MoveUpRight} from 'lucide-react';
import './restaurant.css';
const RestaurantScene=lazy(()=>import('./RestaurantScene'));
const places=[{name:'The table',title:'Good moments start here.',text:'A new favorite. A familiar face. Discover local dining offers and make time for a meal together.'},{name:'The counter',title:'Meet the people behind it.',text:'Every local restaurant has a story. CrazyBee helps connect the people who make it with the people around them.'},{name:'The welcome',title:'Come in. Feel connected.',text:'For diners, a reason to explore. For restaurants, a chance to welcome their next regular.'}];
export default function RestaurantHero({merchant,onAction}:{merchant:boolean;onAction:()=>void}){
 const root=useRef<HTMLElement>(null);const [entered,setEntered]=useState(false),[zone,setZone]=useState<number|null>(null),[revision,setRevision]=useState(0);
 useEffect(()=>{const io=new IntersectionObserver(([e])=>document.documentElement.classList.toggle('hero-in-view',e.isIntersecting),{rootMargin:'-85px 0px -65% 0px'});io.observe(root.current!);return()=>{io.disconnect();document.documentElement.classList.remove('hero-in-view');};},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setEntered(false);setZone(null);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const selected=zone===null?null:places[zone];
 return <section id="world" ref={root} className={'restaurant-hero'+(entered?' is-inside':'')}>
 <div className="restaurant-atmosphere" aria-hidden="true"/><div className="world-index"><span>CRAZYBEE — LOCAL FOOD, REAL CONNECTIONS</span><span>01 — EXPLORE YOUR WAY</span></div><div className="world-theme">A little world. A lot to discover.</div>
 <div className="restaurant-copy world-intro"><div className="world-kicker">{merchant?'FOR THE PLACES THAT BRING US TOGETHER':'GOOD FOOD IS ONLY THE BEGINNING'}</div><h1><span>{merchant?'More new faces.':'A world of flavor.'}</span><span>{merchant?'More familiar ones.':'Closer than you think.'}</span></h1><p>{merchant?'Connect your restaurant with the neighborhood.':'Local discoveries. Lovely little deals. Real connections.'}</p><button className="restaurant-primary" onClick={()=>{if(entered)onAction();else setEntered(true);}}>{entered?(merchant?'Become a partner':'Explore CrazyBee'):'Step inside'}<ArrowUpRight size={18}/></button></div>
 <div className="restaurant-stage"><Suspense fallback={<div className="restaurant-loading">Setting the table…</div>}><RestaurantScene entered={entered} zone={zone} revision={revision} onChoose={setZone} onEnter={()=>setEntered(true)}/></Suspense><span className="restaurant-stage-label">THE NEIGHBORHOOD TABLE <small>AN IMAGINED CRAZYBEE SPACE</small></span></div>
 {entered?<div className="restaurant-explore"><div className="restaurant-explore-top"><button onClick={()=>{setEntered(false);setZone(null);}}><ArrowLeft size={15}/> Back outside</button><button aria-label="Reset restaurant view" onClick={()=>{setZone(null);setRevision(v=>v+1);}}><RotateCcw size={15}/></button></div><div className="restaurant-stops" aria-label="Explore the restaurant">{places.map((p,i)=><button key={p.name} aria-pressed={zone===i} onClick={()=>{setZone(i);setRevision(v=>v+1);}}><small>0{i+1}</small>{p.name}<MoveUpRight size={13}/></button>)}</div><div className="restaurant-place" aria-live="polite"><strong>{selected?.title||'Three corners. A world of connections.'}</strong><p>{selected?.text||'Choose a place above, or click the tables, counter and welcome desk in the scene. Drag to look around.'}</p></div></div>:<div className="restaurant-invite"><p>A little discovery.<br/>A real local connection.</p><button onClick={()=>setEntered(true)}>Click to explore <ArrowUpRight size={14}/></button></div>}
 {entered&&<span className="restaurant-footnote">DRAG TO ORBIT · SCROLL TO ZOOM · ESC TO LEAVE</span>}
 <a href="#the-idea" className="world-scroll">Or, let us introduce ourselves <span>↓</span></a>
 </section>;
}
