import {useEffect,useRef} from 'react';
import * as THREE from 'three';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
export type WorldHandle={turn:(direction:number)=>void;reset:()=>void;focus:(index:number)=>void};
export default function WorldScene({selected,paused,onChoose,onReady,api}:{selected:number|null;paused:boolean;onChoose:(index:number)=>void;onReady:()=>void;api:React.MutableRefObject<WorldHandle|null>}){
 const host=useRef<HTMLDivElement>(null), state=useRef({selected,paused});state.current={selected,paused};const choose=useRef(onChoose);choose.current=onChoose;
 useEffect(()=>{
  const el=host.current;if(!el)return;let renderer:THREE.WebGLRenderer;
  try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});}catch{onReady();return;}
  const dpr=Math.min(devicePixelRatio,1.7);renderer.setPixelRatio(dpr);renderer.setClearColor(0xffffff,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;el.appendChild(renderer.domElement);
  const scene=new THREE.Scene(),world=new THREE.Group();scene.add(world);const camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(0,.2,12);
  const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pmrem.fromScene(room,.04);scene.environment=env.texture;scene.environmentIntensity=.32;room.dispose();pmrem.dispose();scene.add(new THREE.HemisphereLight(0xffe7d1,0x231728,.6));const light=new THREE.DirectionalLight(0xffffff,1.8);light.position.set(-3,5,5);scene.add(light);
  const geometries:THREE.BufferGeometry[]=[],materials:THREE.Material[]=[];
  const uniforms={time:{value:0},pointer:{value:new THREE.Vector2(0,0)},motion:{value:1}};
  // A continuous luminous surface, with broad material ripples instead of loose particles.
  const orbGeometry=new THREE.SphereGeometry(2.07,112,72);geometries.push(orbGeometry);
  const orbMaterial=new THREE.ShaderMaterial({uniforms,vertexShader:`uniform float time;uniform vec2 pointer;varying vec3 vNormal;varying vec3 vPosition;varying vec3 vView;void main(){vec3 p=position;float wave=sin(p.y*3.+time*.28)*sin(p.x*2.4-time*.17)*.07+sin(p.z*4.+p.y*2.+time*.22)*.035;p+=normal*wave;vec4 mv=modelViewMatrix*vec4(p,1.);vNormal=normalize(normalMatrix*normal);vPosition=p;vView=normalize(-mv.xyz);gl_Position=projectionMatrix*mv;}`,fragmentShader:`uniform float time;uniform vec2 pointer;varying vec3 vNormal;varying vec3 vPosition;varying vec3 vView;void main(){vec3 n=normalize(vNormal+vec3(sin(vPosition.y*8.+time*.4),cos(vPosition.z*7.+time*.32),sin(vPosition.x*8.-time*.26))*.035);float edge=pow(1.-max(dot(n,vView),0.),2.3);vec3 light=normalize(vec3(-.6+pointer.x*.2,.8,1.));float diffuse=max(dot(n,light),0.);float ribbon=pow(.5+.5*sin(vPosition.y*3.3+vPosition.x*1.9+time*.18),7.);float pearl=pow(max(dot(reflect(-light,n),vView),0.),24.);vec3 col=mix(vec3(.023,.018,.024),vec3(.12,.057,.052),diffuse);col+=edge*mix(vec3(.32,.11,.09),vec3(.8,.43,.24),smoothstep(-1.,1.,vPosition.y));float silk=exp(-pow(dot(n,normalize(vec3(-.65,.72,.4)))-.48,2.)*360.);float silk2=exp(-pow(dot(n,normalize(vec3(.4,.65,.55)))-.75,2.)*620.);col+=ribbon*.036*vec3(1.,.55,.4)+pearl*.3+silk*vec3(.2,.1,.07)+silk2*vec3(.06,.07,.09);gl_FragColor=vec4(col,1.);
#include <colorspace_fragment>
}`});materials.push(orbMaterial);const orb=new THREE.Mesh(orbGeometry,orbMaterial);orb.position.set(0,.25,-1.05);world.add(orb);
  const rim=new THREE.DirectionalLight(0xff5a35,4);rim.position.set(2,1,-4);scene.add(rim);const fill=new THREE.DirectionalLight(0xa8bbff,.7);fill.position.set(-4,1,1);scene.add(fill);
  // An elliptical studio reflection grounds the floating composition.
  const shadowCanvas=document.createElement('canvas');shadowCanvas.width=256;shadowCanvas.height=256;const ctx=shadowCanvas.getContext('2d')!;const gradient=ctx.createRadialGradient(128,128,0,128,128,128);gradient.addColorStop(0,'rgba(244,92,59,0.22)');gradient.addColorStop(.45,'rgba(161,57,45,0.09)');gradient.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,256,256);const shadowTexture=new THREE.CanvasTexture(shadowCanvas);const shadowGeometry=new THREE.PlaneGeometry(6,1.1);geometries.push(shadowGeometry);const shadowMaterial=new THREE.MeshBasicMaterial({map:shadowTexture,transparent:true,depthWrite:false});materials.push(shadowMaterial);const shadow=new THREE.Mesh(shadowGeometry,shadowMaterial);shadow.position.set(0,-2.03,-.6);world.add(shadow);
  // The hero and food sculptures are complete meshes, visible from every direction.
  const models:THREE.Group[]=[];const portrait=new THREE.Group();portrait.position.set(0,.15,.75);world.add(portrait);models.push(portrait);
  const mascotTexture=new THREE.TextureLoader().load('/assets/crazybee-cutout.png');mascotTexture.colorSpace=THREE.SRGBColorSpace;const mascotMaterial=new THREE.SpriteMaterial({map:mascotTexture,transparent:true,depthWrite:false,depthTest:false,toneMapped:false});const mascot=new THREE.Sprite(mascotMaterial);mascot.renderOrder=5;mascot.scale.set(3.7,3.7,1);portrait.add(mascot);materials.push(mascotMaterial);
  const resize=()=>{const b=el.getBoundingClientRect();renderer.setSize(b.width,b.height);camera.aspect=b.width/b.height;camera.updateProjectionMatrix();};const ro=new ResizeObserver(resize);ro.observe(el);resize();
  let target=0,drag=false,px=0,py=0,moved=0,active=true,time=0,previous=0,frame=0;const pointer=new THREE.Vector2(0,0);const rotations=models.map(()=>new THREE.Vector2(0,0));api.current={turn:d=>{rotations[target].x+=d*Math.PI/4;},reset:()=>{rotations.forEach(r=>r.set(0,0));pointer.set(20,20);},focus:index=>{target=index;}};
  const move=(e:PointerEvent)=>{const b=el.getBoundingClientRect();pointer.set((e.clientX-b.left)/b.width*2-1,1-(e.clientY-b.top)/b.height*2);uniforms.pointer.value.set(pointer.x*4,pointer.y*3);if(drag){rotations[target].x+=(e.clientX-px)*.009;rotations[target].y=THREE.MathUtils.clamp(rotations[target].y+(e.clientY-py)*.007,-1.1,1.1);moved+=Math.abs(e.clientX-px)+Math.abs(e.clientY-py);px=e.clientX;py=e.clientY;}};
  const down=(e:PointerEvent)=>{move(e);drag=true;px=e.clientX;py=e.clientY;moved=0;el.setPointerCapture(e.pointerId);};const up=()=>{drag=false;};const leave=()=>{pointer.set(20,20);uniforms.pointer.value.set(0,0);};el.addEventListener('pointermove',move);el.addEventListener('pointerdown',down);el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up);el.addEventListener('pointerleave',leave);
  const io=new IntersectionObserver(([e])=>active=e.isIntersecting);io.observe(el);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const animate=(now:number)=>{frame=requestAnimationFrame(animate);const dt=Math.min((now-previous)/1000,.04);previous=now;if(!active||document.hidden)return;if(!state.current.paused&&!reduced)time+=dt;uniforms.time.value=time;uniforms.motion.value=reduced||state.current.paused?0:1;const mobile=el.clientWidth<600,expanded=state.current.selected!==null&&!mobile;camera.position.z=THREE.MathUtils.lerp(camera.position.z,mobile?15.8:12,.045);world.position.y=mobile?.95:.55;portrait.scale.setScalar(mobile?.9:1);world.position.x=THREE.MathUtils.lerp(world.position.x,expanded?-1.3:0,.05);models.forEach((m,i)=>{m.rotation.y=THREE.MathUtils.lerp(m.rotation.y,rotations[i].x,.09);m.rotation.x=THREE.MathUtils.lerp(m.rotation.x,rotations[i].y,.09);});orb.rotation.y=THREE.MathUtils.lerp(orb.rotation.y,rotations[0].x+Math.sin(time*.15)*.18,.06);orb.rotation.x=THREE.MathUtils.lerp(orb.rotation.x,rotations[0].y,.06);orb.rotation.z=Math.sin(time*.12)*.04;orb.scale.setScalar(1+Math.sin(time*.38)*.014);renderer.render(scene,camera);};frame=requestAnimationFrame(animate);onReady();
  return()=>{cancelAnimationFrame(frame);ro.disconnect();io.disconnect();el.removeEventListener('pointermove',move);el.removeEventListener('pointerdown',down);el.removeEventListener('pointerup',up);el.removeEventListener('pointercancel',up);el.removeEventListener('pointerleave',leave);geometries.forEach(g=>g.dispose());new Set(materials).forEach(m=>m.dispose());mascotTexture.dispose();shadowTexture.dispose();env.dispose();renderer.dispose();renderer.domElement.remove();api.current=null;};
 },[]);
 return <div className="world-canvas" ref={host} role="img" aria-label="CrazyBee brand world. Original plush mascot with a flowing light sculpture. Drag to move the surrounding light."/>;
}
